/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
 
export default function Cauldron(props) {
  const { nodes, materials } = useGLTF('/cauldron.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mesh.geometry}
        material={materials.DefaultMaterial}
        position={[1.396, 1.134, -0.205]}
        rotation={[-1.415, -0.356, 0.468]}
        scale={20.496}
      />
    </group>
  )
}

useGLTF.preload('/cauldron.glb')
